            
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DEL_MESSAGE = 'DEL_MESSAGE';
export const LOAD_ALL_EMPLOYEES_SUCCESS = 'LOAD_ALL_EMPLOYEES_SUCCESS';
export const LOAD_EMPLOYEE_SUCCESS = 'LOAD_EMPLOYEE_SUCCESS';
export const LOAD_EMPLOYEE_DETAIL_SUCCESS = 'LOAD_EMPLOYEE_DETAIL_SUCCESS';
export const CLEAR_EMPLOYEE_STATE = 'CLEAR_EMPLOYEE_STATE';
export const LOAD_USER_SETTINGS_SUCCESS = 'LOAD_USER_SETTINGS_SUCCESS';
export const SORT_BY_FIRSTNAME = 'SORT_BY_FIRSTNAME';
export const SORT_BY_MIDDLENAME = 'SORT_BY_MIDDLENAME';
export const SORT_BY_LASTNAME = 'SORT_BY_LASTNAME';
export const SORT_BY_DATEOFBIRTH = 'SORT_BY_DATEOFBIRTH';
export const ORDER_BY_ASC = "ORDER_BY_ASC";
export const ORDER_BY_DESC = "ORDER_BY_DESC";



