            
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DEL_MESSAGE = 'DEL_MESSAGE';
export const LOAD_EMPLOYEES_SUCCESS = 'LOAD_EMPLOYEES_SUCCESS';
export const LOAD_USER_SETTINGS_SUCCESS = 'LOAD_USER_SETTINGS_SUCCESS';
