
export const FAKEEMPLOYEEDATA = [ 
    {
      "xid": "b7lc88eq3m0g00f9tosg",
      "statuscode": 200,
      "response": [
          {  id: '1', 
          source: 'OIG',
          firstName: 'August',
          lastName: 'Lubowitz',
          dob: '1983-2-26',
          title: 'District Usability Supervisor',
          offence: 'Clear' },
        { id: '2', 
          source: 'OIG',
          firstName: 'Amir',
          lastName: 'Friesen',
          dob: '1944-4-17',
          title: 'Global Applications Strategist',
          offence: 'Clear' },
        { id: '3', 
        source: 'SAM',
          firstName: 'Roma',
          lastName: 'Homenick',
          dob: '1964-1-2',
          title: 'National Implementation Administrator',
          offence: 'Consider' },
        { id: '4', 
          source: 'OIG',
          firstName: 'Elmore',
          lastName: 'McClure',
          dob: '1966-9-10',
          title: 'Internal Factors Representative',
          offence: 'Consider' },
        { id: '5', 
          source: 'OIG',
          firstName: 'Roman',
          lastName: 'Auer',
          dob: '1978-6-2',
          title: 'Legacy Research Executive',
          offence: 'Clear' },
        { id: '6', 
          source: 'OIG',
          firstName: 'Jacky',
          lastName: 'Schinner',
          dob: '1987-5-19',
          title: 'Internal Operations Manager',
          offence: 'Clear' },
        { id: '7', 
          source: 'OIG',
          firstName: 'Brody',
          lastName: 'Kirlin',
          dob: '1987-5-19',
          title: 'Investor Integration Strategist',
          offence: 'Clear' },
        { id: '8', 
          source: 'OFAC',
          firstName: 'Ezequiel',
          lastName: 'Kulas',
          dob: '1977-5-25',
          title: 'Legacy Infrastructure Orchestrator',
          offence: 'Consider' },
        { id: '9', 
          source: 'SAM',
          firstName: 'Johnson',
          lastName: 'Maggio',
          dob: '1985-12-3',
          title: 'Human Implementation Director',
          offence: 'Consider' },
        { id: '10', 
          source: 'OIG',
          firstName: 'Sheila',
          lastName: 'Ebert',
          dob: '1967-3-11',
          title: 'Senior Division Coordinator',
          offence: 'Consider' },
        { id: '11', 
          source: 'OIG',
          firstName: 'Fern',
          lastName: 'Legros',
          dob: '1970-1-14',
          title: 'Principal Web Officer',
          offence: 'Clear' },
        { id: '12', 
          source: 'OFAC',
          firstName: 'Rebeca',
          lastName: 'Hudson',
          dob: '1953-10-13',
          title: 'Global Accounts Specialist',
          offence: 'Clear' },
        { id: '13', 
          source: 'OIG',
          firstName: 'Justus',
          lastName: 'Kuhlman',
          dob: '1979-3-17',
          title: 'Forward Operations Assistant',
          offence: 'Consider' },
        { id: '14', 
          source: 'OIG',
          firstName: 'Kyla',
          lastName: 'Deckow',
          dob: '1943-10-11',
          title: 'Investor Security Producer',
          offence: 'Consider' },
        { id: '15', 
          source: 'OIG',
          firstName: 'Kassandra',
          lastName: 'VonRueden',
          dob: '1961-7-10',
          title: 'International Paradigm Planner',
          offence: 'Clear' },
        { id: '16', 
          source: 'OFAC',
          firstName: 'Ruth',
          lastName: 'West',
          dob: '1970-12-13',
          title: 'National Identity Strategist',
          offence: 'Clear' },
        { id: '17', 
          source: 'SAM',
          firstName: 'Makayla',
          lastName: 'Mosciski',
          dob: '1991-10-16',
          title: 'Senior Configuration Facilitator',
          offence: 'Clear' },
        { id: '18', 
          source: 'OIG',
          firstName: 'Tracy',
          lastName: 'Mante',
          dob: '1965-7-10',
          title: 'International Brand Developer',
          offence: 'Consider' },
        { id: '19', 
          source: 'SAM',
          firstName: 'Emma',
          lastName: 'Tremblay',
          dob: '1983-6-17',
          title: 'Regional Optimization Analyst',
          offence: 'Consider' },
        { id: '20', 
          source: 'OIG',
          firstName: 'Finn',
          lastName: 'Friesen',
          dob: '1949-3-23',
          title: 'Forward Implementation Executive',
          offence: 'Clear' }
      ]
  } 
];